jprichardson/node-fs-extra

README.md

I noticed the links to section titles were broken, so I fixed them. Hope it helps!

Update section links in README to match current section ids.

---

.travis.yml

Travis recently introduced a new container infrastructure which reduces queueing time for builds/test runs significantly.
This PR adds a line to the Travis config file to take advantage of this.

Travis runs with `sudo: false`

---

README.md

I was confused by the description so I propose to commit a clearer version.

A clearer description of emtpyDir function

---

lib/copy/__tests__/copy.test.js
lib/copy/copy.js

throw error if src and dest are the same to avoid zeroing out + test

---

README.md

in favour of https://github.com/jprichardson/node-fs-extra/commit/5747fb303ae2afb939f3cd936673075543c15d6e

Remove link to createOutputStream

---

lib/copy-sync/copy-file-sync.js

Improve EEXIST error message for copySync

---

lib/copy-sync/copy-sync.js
lib/copy/copy.js

Warn about using preserveTimestamps on 32-bit node

---

README.md

Fixes #239 
Attn: @jprichardson

Depreciate using regular expressions for copy's filter option

---

lib/copy-sync/__tests__/copy-sync-dir.test.js
lib/copy-sync/__tests__/copy-sync-file.test.js
lib/copy-sync/copy-sync.js
lib/copy/__tests__/copy.test.js
lib/copy/ncp.js

Followup of https://github.com/jprichardson/node-fs-extra/pull/295.

Warn when filter is a RegExp

---

lib/copy-sync/copy-file-sync.js

This should resolve https://github.com/jprichardson/node-fs-extra/issues/199.

Remove chmod call from copySync

---

README.md

Refs https://github.com/jprichardson/node-fs-extra/issues/180#issuecomment-257016134

Document copySync filter inconsistency

---

lib/ensure/symlink-paths.js
package.json

@jprichardson Anything else for v1.0.0?

Remove path-is-absolute

---

README.md
lib/move/index.js

Fixes https://github.com/jprichardson/node-fs-extra/issues/314.

Remove move()'s broken limit option

---

lib/copy-sync/__tests__/copy-sync-file.test.js

Adding test coverage to cover case I thought previously was a bug

Adding copy sync test for src file without write perms

---

lib/move/index.js

@jprichardson Reading the source code, I found a little cleanup that needed done.

Cleanup lib/move/index.js

---

docs/copy.md
docs/emptyDir.md
docs/ensureDir.md
docs/ensureFile.md
docs/ensureLink.md
docs/ensureSymlink.md
docs/move.md
docs/outputFile.md
docs/outputJson.md
docs/readJson.md
docs/remove.md
docs/writeJson.md

(#355)
Refactored `./docs` code to ES6 and improved the docs code consistency.

Refactor docs to ES6

---

lib/copy/__tests__/copy-dev-null.test.js

Refs: #370.
I edited the description to match the test.

Edit copy-dev-null test description

---

README.md
docs/copy-sync.md
docs/emptyDir-sync.md
docs/ensureDir-sync.md
docs/ensureFile-sync.md
docs/ensureLink-sync.md
docs/ensureSymlink-sync.md
docs/move-sync.md
docs/move.md
docs/outputFile-sync.md
docs/outputFile.md
docs/outputJson-sync.md
docs/outputJson.md
docs/readJson-sync.md
docs/remove-sync.md
docs/writeJson-sync.md
docs/writeJson.md

Refs: #148.
Please let me know if there is any issues :smile:

Docs: Split out sync methods

---

docs/copy-sync.md
docs/copy.md
docs/emptyDir-sync.md
docs/emptyDir.md
docs/ensureDir-sync.md
docs/ensureDir.md
docs/ensureFile-sync.md
docs/ensureFile.md
docs/ensureLink-sync.md
docs/ensureLink.md
docs/ensureSymlink-sync.md
docs/ensureSymlink.md
docs/move-sync.md
docs/move.md
docs/outputFile-sync.md
docs/outputFile.md
docs/outputJson-sync.md
docs/outputJson.md
docs/readJson-sync.md
docs/readJson.md
docs/remove-sync.md
docs/remove.md
docs/writeJson-sync.md
docs/writeJson.md

Because of the issues like #348, also to provide a little more clarification regarding parameters type. I'd like to know what you think :smile:

Refactor docs to include parameters type

---

CHANGELOG.md

@jprichardson Let me know if I missed anything.
Refs https://github.com/jprichardson/node-fs-extra/issues/385.

Update CHANGELOG for v2.1.0 release

---

lib/remove/rimraf.js

Prevent callback from being called twice

---

lib/remove/rimraf.js

Fixes https://github.com/jprichardson/node-fs-extra/issues/407

Add else block to throw error from catch in removeSync()

---

docs/outputJson-sync.md
docs/outputJson.md
docs/writeJson-sync.md
docs/writeJson.md

Document writeJson() & outputJson() options

---

lib/remove/rimraf.js

https://github.com/isaacs/rimraf/commit/e8b10a79c25e84f2a017e8a38b0725d8a0b259d3
https://github.com/isaacs/rimraf/commit/d53235de863cfb00f691456288fcf3abbced7f6c
https://github.com/isaacs/rimraf/commit/e8cd6853ba5cd47c53073af5bc9c17f88457bed4

Apply upstream rimraf fixes

---

.travis.yml
appveyor.yml
package.json

- Test on Node 8
- Only run unit tests on Appveyor
- Optimize TravisCI builds to use the minimum number of containers while keeping the performance reasonable

Update & Optimize CI configs

---

docs/outputJson-sync.md
docs/outputJson.md
docs/writeJson-sync.md
docs/writeJson.md
lib/__tests__/promise.test.js
lib/fs/__tests__/copyFile.test.js
lib/fs/index.js
lib/json/__tests__/jsonfile-integration.test.js
lib/json/__tests__/promise-support.test.js
package.json

This is slated for a patch release, hopefully today, but I want some peer review beforehand.

Developments for patch release

---

docs/fs-read-write.md

[documentation] typo found and fixed

---

.github/issue_template.md
.npmignore

Added issue template. I am not sure about the wording though! Please change it any way that you think is appropriate! :smile:

Add issue template

---

lib/copy/copy.js

Applied the async filter to initial filter checking, before start copying.

Apply the async filter to initial filter checking in copy

---

README.md

Added a link to the [fs-filesystem](https://github.com/arthurintelligence/node-fs-filesystem) external library for reference.
References #504 
🚀

docs(README.md) Linked to fs-filesystem external library

---

README.md

Add docs that graceful-fs is used

---

lib/fs/index.js

Add missing element for `fs.lchmod` promisification (#595)

---

.github/issue_template.md

Seems like couple of issues are due to an old version of `fs-extra`. This might help. I'm not native in english, so the second sentence can be improved indeed (two if's in one sentence? 😅)

Chore: github issue template

---

.npmignore

These files are not necessary.
Closes #642

Added docs/ and CHANGELOG.md to .npmignore (#642)

---

CHANGELOG.md

https://stackoverflow.com/questions/9208091/the-difference-between-deprecated-depreciated-and-obsolete#answer-9208164

doc: fix typo: depreciated -> deprecated

---

docs/remove-sync.md
docs/remove.md

Clarify docs for remove*()

---

lib/copy-sync/copy-sync.js
lib/copy/copy.js
lib/empty/index.js
lib/move-sync/move-sync.js
lib/move/__tests__/move.test.js
lib/move/move.js
lib/util/stat.js
package.json

New version of graceful-fs has fixes for stat.

Use graceful-fs everywhere

---

lib/util/__tests__/stat.test.js

Not sure why linter didn't catch this

Remove unused done param

---

docs/ensureLink-sync.md
docs/ensureLink.md
docs/ensureSymlink-sync.md
docs/ensureSymlink.md

Document all create*() aliases for ensure*() methods

---

package.json

https://github.com/RyanZim/universalify/releases

Upgrade universalify

---

lib/mkdirs/make-dir.js
lib/mkdirs/utils.js

Moved last bit of make-dir code to its own file
Refs https://github.com/jprichardson/node-fs-extra/issues/886
After https://github.com/jprichardson/node-fs-extra/pull/893

BREAKING: Use native fs.mkdir recursive everywhere

---

package.json

Move at-least-node to devDependencies

---

package.json

Will merge in a few days if no objection

Upgrade standard linter
