- lib/move.js
Some versions of Linux (including on the Travis container infrastructure) throw an EEXIST error rather than ENOTEMPTY when you try to overwrite a directory while renaming, and that wasn't being handled.
This PR fixes that.
> Handle EEXIST error when clobbering dir

- test.js
fix `test.js` implementation mentioned in #144
This PR ensures that tests are:
- only found in `fs-extra/lib`
- found even if `fs-extra` is in a `node_modules` folder
> ensure test.js works

- lib/ensure/__tests__/link.test.js
- lib/ensure/__tests__/symlink.test.js
- lib/ensure/link.js
- lib/ensure/symlink.js
Here's the dest error suppressing for ensureLink thoughts? I'd do the same for ensureSymlink
> suppress ensureLink & ensureSymlink dest exists error

- lib/move/__tests__/move.test.js
- lib/move/index.js
Discovered while investigating
https://github.com/Medium/phantomjs/issues/341
where moving a directory across virtual drives caused an
EXDEV error that shunted things down the "move file"
instead of "move directory" codepath
> More robust handling of errors moving across virtual drives

- lib/move/__tests__/move.test.js
move.test modified to support testing files with both LF (NIX) and CRLF (Windows) line endings. This commit fixes #188.
> move.test fix to support CRLF on Windows

- lib/copy-sync/__tests__/copy-sync-file.test.js
- lib/copy-sync/copy-file-sync.js
copySync updated to overwrite destination file if readonly and clobber set to true. Added test case. This commit fixes #183.
> copySync to overwrite destination file if readonly and clobber true

- lib/copy/ncp.js
allow copying of character or block devices (NB: copies contents, not the inode)
> allow copy of block and character device files

- README.md
> Fixing copySync anchor tag

- lib/copy/copy.js
I have a lot of legacy code which uses old version(0.12.0) of fs-extra.
Old code does not work with new fs-extra due to it uses fse.copy with only 2 arguments `src` and `dest`.
Let's improve backward compatibility, guys
> fse.copy throws error when only src and dest provided

- README.md
A tiny fix for the example code of `fs.copySync()` in the README.
> Add closing parenthesis in copySync example

- README.md
- lib/copy-sync/__tests__/broken-symlink.test.js
- lib/copy-sync/__tests__/symlink.test.js
- lib/copy-sync/copy-sync.js
Carries forward the behavior and specs governing the existing (async-only) implementation and updates the documentation.
Thanks for considering this change!
> Adds symlink dereference option to `fse.copySync` (#191)

- README.md
This wasn’t obvious to me.
Thought it’s worth documenting!
> Mention defaults for clobber and dereference options

- lib/remove/index.js
Its important to pass the options through as ensuring symmetry between the `fs.extra#remove` and `rimraf` APIs means I don't need to include `rimraf` AND `fs-extra`, just for the sake of using `rimraf` with specific options.
One option that is particularly useful and quite commonly used is `disableGlob`.
> Disable rimraf globbing

- lib/util/__tests__/utimes.test.js
- lib/util/utimes.js
- package.json
I made one other change in utimes.js to ensure that the callback for `utimesMillis` is only called after the file has been closed.
> (Closes #271) lib/util/utimes: properly close file descriptors in the event of an error

- lib/copy/__tests__/copy.test.js
- lib/copy/ncp.js
Change made in /lib/copy/ncp.js to the string.replace in the onFile function
Fixes #242.
> Escape '$' in replacement string for async file copying

- lib/copy/__tests__/ncp/broken-symlink.test.js
- lib/copy/__tests__/ncp/ncp-error-perm.test.js
- lib/copy/__tests__/ncp/ncp.test.js
- lib/copy/ncp.js
@jprichardson Looking at https://github.com/jprichardson/node-fs-extra/issues/292, I decided to just do a fairly major refactor instead of a total rewrite.
Changes:
- Fix #233 - First argument passed to callback should be an Error object, not an array.
- Fix #272 - Should error when options.clobber is false and the destination exists.
- Remove options.limit, it is no longer needed with graceful-fs.
---
A test fails on windows, node v0.10:
```
1 failing
1) ncp regular files and directories when using transform file descriptors are passed correctly:
Uncaught AssertionError: null == true
at C:\projects\node-fs-extra\lib\copy\__tests__\ncp\ncp.test.js:103:13
at doneOne (C:\projects\node-fs-extra\lib\copy\ncp.js:226:16)
at C:\projects\node-fs-extra\lib\copy\ncp.js:89:11
at …
```
> BREAKING: Refactor lib/copy/ncp.js

- lib/move/index.js
- lib/remove/index.js
- lib/remove/rimraf.js
- package.json
We aren't using rimraf's glob support, and glob is a rather large dependency.
Changes:
- Remove glob support from rimraf
- Remove move()'s dependency on rimraf; use fs-extra.remove instead
- Make rimraf a devDependency; it is used in the tests
---
**Original comment:**
@jprichardson This is my WIP of inlining rimraf. This needs rebased, **do not merge**.
rimraf has functionality built in to handle alternate `fs` modules. Currently, there is no way for the end-user to leverage that functionality. I could simplify the code by removing that, however, I don't want to have to add it back. Will we be adding custom `fs` module support or glob support to `fs-extra` first?
> Inline Rimraf

- lib/util/__tests__/utimes.test.js
- package.json
@jprichardson Ever think of using @greenkeeperio-bot so I don't have to do this? I use it on all of my projects and really like it. Not only does it update dependencies outside your version range, it also checks to make sure none of your dependencies break semver.
My only gripe is the commit messages: `chore(package): update eslint to version 3.8.0`. I always use the squash-merge function so I can reword the commit message to `Update eslint to version 3.8.0`.
https://greenkeeper.io/
> Update devDeps, fix lint error

- .travis.yml
@jprichardson Not sure if this is the best way, as it runs the tests twice. Other ways:
- Only run `coveralls` on the `LINT` build.
- Run the coverage script as the main script, and modify the coveralls script to only use the existing coverage report.
- Write a custom travis script in JS that runs tests for every platform and runs `standard` and `coveralls` on only one version.
Thoughts?
> Re-add Coveralls

- .travis.yml
- package.json
- istanbul shouldn't include test files in the coverage report
- Run coveralls only on the lint build in Travis CI
Coverage is pretty low, mainly due to window-specific code. How would coveralls handle it if we ran it on appveyor as well? Coverage would be higher there.
> Fix coverage

- lib/move/__tests__/move-clobber.test.js
When trying to rename a directory over another directory, graceful-fs-4.1.10
(maybe other versions?) takes 1 minute to fail the call with an error.
This causes the test to timeout. The workaround is to increase the timeout
of that one test to 1m30s.
See https://github.com/isaacs/node-graceful-fs/issues/98
> Fix move clobber tests to work around graceful-fs bug.

- lib/remove/__tests__/remove.test.js
After looking at rimraf, I began to fear that node-fs-extra, which
is based on rimraf, might also automatically glob things. I find
this confusing when the API is being used as an overlay of the
node built-in fs module which never expands globs. This test
explicitly verifies that the remove() function does not follow
glob characters.
> Test that remove() ignores glob characters.

- lib/walk-sync/__tests__/walkSync.test.js
- lib/walk-sync/index.js
Hi,
This PR is regarding #310. I modified `walkSync` and its test to return an array of items `{path:,stats:}` to be consistent with `walk`. Please let me know what you think. I appreciate it in advance. Thanks a lot.
> Enhance walkSync() to return items with path and stats

- lib/copy-sync/__tests__/copy-sync-dir.test.js
- lib/copy-sync/copy-sync.js
Fixes #180 
Had to change a incorrectly written test.
@jprichardson ?
> copySync() should apply filter to directories like copy()

- lib/copy/ncp.js
Fixes https://github.com/jprichardson/node-fs-extra/issues/326
> Use writeStream 'finish' event instead of 'close'

- README.md
- lib/copy-sync/__tests__/copy-sync-file.test.js
- lib/copy-sync/copy-file-sync.js
- lib/copy-sync/copy-sync.js
- lib/copy/__tests__/ncp/ncp.test.js
- lib/copy/ncp.js
Add errorOnExist option for users that want an error
Resolves #321 
@jprichardson What do you think of the error message?
> BREAKING: Do not error when copy destination exists & clobber: false

- README.md
- lib/copy-sync/__tests__/copy-sync-file.test.js
- lib/copy-sync/copy-file-sync.js
- lib/copy-sync/copy-sync.js
- lib/copy/__tests__/ncp/ncp.test.js
- lib/copy/ncp.js
- lib/move/__tests__/move-clobber.test.js
- lib/move/__tests__/move.test.js
- lib/move/index.js
Keep clobber for backwards compatibility
Fixes #172
> Rename clobber to overwrite

- README.md
This resolves #338.
It adds https://github.com/mawni/node-klaw-sync link to the readme.
> Add klaw-sync link to readme

- README.md
This PR updates `klaw-sync` link in README. I changed my username from `mawni` to `manidlou`, so I updated the `klaw-sync` link to the new one https://github.com/manidlou/node-klaw-sync. Sorry for inconvenience. Thanks a lot.
> Update klaw-sync link in readme

- lib/copy-sync/copy-file-sync.js
- lib/copy-sync/copy-sync.js
- lib/copy/copy.js
- lib/empty/index.js
- lib/ensure/file.js
- lib/ensure/index.js
- lib/ensure/link.js
I refactored some files to ES6 according to #355 . Much things are not available in Node v4.
`'use strict'` is a must in Node v4 if `let` is used. For consistency I also put it although no `let` is used.
> ES6 refactoring

- README.md
- lib/ensure/symlink-paths.js
- lib/ensure/symlink-type.js
- lib/ensure/symlink.js
- lib/index.js
- lib/json/index.js
- lib/json/jsonfile.js
- lib/json/output-json-sync.js
- lib/json/output-json.js
- lib/mkdirs/mkdirs-sync.js
- lib/mkdirs/mkdirs.js
- lib/mkdirs/win32.js
- lib/output/index.js
- lib/remove/index.js
- lib/util/assign.js
- lib/util/utimes.js
(#355 )  I did some more refactoring. Now everything except `move/index`, `copy/ncp` and `remove/rimraf` are as much as possible refactored to ES6. I wasn't sure on the skipped files, as they are from another library or got a comment with something like `needs rewrite` or similar.
> ES6 refactor

- lib/move/index.js
- lib/remove/rimraf.js
(#355)
`move`:
I renamed the function from `mv` to `move`, it shouldn't be a breaking change
`rimraf`:
Here I put `module.exports` to the end of the file, as it is the same in all other files. Also I refactored one line `if`-statements, also with the same reason that it is the same in all other files.
---
I skipped `copy/ncp` as discussed in https://github.com/jprichardson/node-fs-extra/pull/360#issuecomment-280857354. Now I will start with the tests, unless I missed anything. I will make a pull request for each folder (`copy`, `copy-sync`, ...) if that is ok for you.
> Refactor move / rimraf to ES6

- lib/__tests__/fs-integration.test.js
- lib/copy-sync/__tests__/broken-symlink.test.js
- lib/copy-sync/__tests__/copy-sync-dir.test.js
- lib/copy-sync/__tests__/copy-sync-file.test.js
- lib/copy-sync/__tests__/copy-sync-preserve-time.test.js
- lib/copy-sync/__tests__/symlink.test.js
- lib/copy/__tests__/async/copy-gh-89.test.js
- lib/copy/__tests__/copy-dev-null.test.js
- lib/copy/__tests__/copy-permissions.test.js
- lib/copy/__tests__/copy-preserve-time.test.js
- lib/copy/__tests__/copy.test.js
- lib/copy/__tests__/ncp/broken-symlink.test.js
- lib/copy/__tests__/ncp/ncp-error-perm.test.js
- lib/copy/__tests__/ncp/ncp.test.js
- lib/copy/__tests__/ncp/symlink.test.js
> Refactor tests copy/copy-sync to ES6

- lib/copy/__tests__/copy.test.js
- lib/empty/__tests__/empty-dir-sync.test.js
- lib/empty/__tests__/empty-dir.test.js
- lib/ensure/__tests__/create.test.js
- lib/ensure/__tests__/ensure.test.js
- lib/ensure/__tests__/link.test.js
- lib/ensure/__tests__/symlink-paths.test.js
- lib/ensure/__tests__/symlink-type.test.js
- lib/ensure/__tests__/symlink.test.js
- lib/json/__tests__/jsonfile-integration.test.js
- lib/json/__tests__/output-json-sync.test.js
- lib/json/__tests__/output-json.test.js
- lib/json/__tests__/read.test.js
- lib/json/__tests__/spaces.test.js
- lib/output/__tests__/output.test.js
- lib/util/__tests__/utimes.test.js
- package.json
(#355)
In commit https://github.com/jprichardson/node-fs-extra/commit/55aadcf1f1871200535c349e82e33c4b55c3337f I removed `semver`, as dependency as it was just used to ignore Node v0.10.
> Refactor tests to ES6

- docs/copy.md
- lib/copy-sync/__tests__/copy-sync-dir.test.js
- lib/copy-sync/copy-sync.js
- lib/copy/__tests__/copy.test.js
- lib/copy/ncp.js
This resolves #351.
I added dest as an additional parameter to filter option in both `copy` and `copySync`.
> Add dest parameter to filter option in copy and copySync

- docs/copy.md
Refactored the copy filter example since it wasn't in the es6 style.
> docs/copy.md: Refactor copy filter example

- test.js
I totally forgot one file to refactor 😅 
`.on('end', () => ...)` can be written as one liner, but there is no real benefit, as it is harder to read.
Thanks again for this awesome library and that I could help you out 👍
> Refactor test.js

- lib/move/index.js
`move()` should fall back to using streams when `fs.link()` fails with `ENOTSUP`, just as it already does for `EPERM` and other errors.
(As discussed in nodejs/node#11663, hard links aren't supported on ReFS.)
> move(): fall back to streams when hard links aren't supported

- docs/outputFile.md
`fs.writeFile()` supports a buffer or a file descriptor as 1st  argument (`file`), but `fs-extra.outputFile()` does not. Because it sends `file` parameter to `path.dirname()` that requires `String`.
> Document `outputFile()` only supports a file path

- lib/copy-sync/copy-file-sync.js
- package.json
Since `new Buffer()` is deprecated, https://nodejs.org/api/buffer.html#buffer_new_buffer_size, I updated `lib/copy-sync/copy-file-sync.js` to use `Buffer.alloc()` instead of deprecated `new Buffer()`.
> Use Buffer.alloc() instead of deprecated new Buffer() in copy-file-sync

- docs/readJson.md
- lib/move-sync/__tests__/move-sync.test.js
- lib/move/__tests__/move.test.js
This one missed! Plus a few minor refactor for `move` and `moveSync` test descriptions.
> Refactor docs example for readJson()

- lib/move/__tests__/move.test.js
- lib/move/index.js
This PR addresses #377 to avoid a move operation if the `source` and `dest` paths are the same.
*(I'll add tests too, just wanted to get the ball rolling)*
> Don't move when source and dest paths are the same.

- lib/copy-sync/copy-file-sync.js
- lib/move-sync/index.js
- lib/util/buffer.js
Resolves https://github.com/jprichardson/node-fs-extra/issues/391
> Use Buffer.allocUnsafe() in enviroments that support it

- lib/move-sync/__tests__/move-sync.test.js
- lib/move/__tests__/move.test.js
This issue with graceful-fs has been fixed, so no need for this.
> Don't override move test timeout

- CHANGELOG.md
Fixed a few markdown issues in `CHANGELOG.md` file.
> Fix changelog markdown issues

- README.md
- docs/copy.md
- docs/emptyDir.md
- docs/ensureDir.md
- docs/ensureFile.md
- docs/ensureLink.md
- docs/ensureSymlink.md
- docs/move.md
- docs/outputFile.md
- docs/outputJson.md
- docs/readJson.md
- docs/remove.md
- docs/writeJson.md
- package.json
Added [standard-markdown](https://github.com/zeke/standard-markdown) to lint js code blocks inside our markdown files. Since `standard-markdown` uses `standard`, we have a consistent linter for both js and markdown files.
`standard-markdown` by default comes with a few eslint rules disabled. Just added one more rule [handle-callback-err](http://eslint.org/docs/rules/handle-callback-err) to the list of `disabledRules` in `standard-markdown` source code. I guess for us, it makes sense to disable that rule on markdown files.
> Add standard-markdown to lint js code in markdown files

- lib/move-sync/__tests__/move-sync.test.js
- lib/move-sync/index.js
- lib/move/__tests__/move.test.js
- lib/move/index.js
Fixes #414; bug introduced in #378
@jprichardson What's your opinion on semver for this patch?
> move() should error when src & dest are the same and src doesn't exist

- lib/json/index.js
Reorganize file to put async methods first
Fixes https://github.com/jprichardson/node-fs-extra/issues/427
> Fix typo that broke outputJSONSync()

- lib/copy-sync/__tests__/copy-sync-preserve-time.test.js
- lib/copy/__tests__/copy-preserve-time.test.js
This should get appveyor passing
> Skip copy & copySync timestamp tests on 32-bit computers

- lib/move/__tests__/move-prevent-moving-into-itself.test.js
- lib/move/__tests__/move.test.js
- lib/move/index.js
Fixed the issue with `move()` when dest is a subdirectory of src. Also, removed `shouldMkdirp` option as we discussed before.
To quickly remind the issue, with existing behavior, running something like this
```js
const src = 'src'
const dest = 'src/dest'
fs.move(src, dest, err => {
if (err) return console.log(err)
console.log('done.')
})
```
results in just removing `src` and essentially losing all `src` contents.
I believe we should prevent this from happening. Any feedback appreciated!
> Prevent move into itself

- README.md
- docs/fs-read-write.md
- lib/fs/__tests__/multi-param.test.js
- lib/fs/index.js
- package.json
For forward-compat with `util.promisify()`
Resolves https://github.com/jprichardson/node-fs-extra/issues/436
Needs docs yet
> BREAKING: fs.read() & fs.write() should return objects

- CHANGELOG.md
Fixed `CHANGELOG.md` latest `move()` notes.
> Fix changelog move() notes

- lib/ensure/__tests__/ensure.test.js
- lib/ensure/file.js
Fixes #465 
If testing locally, make sure to run `npm update` first; I discovered a bug in universalify while working on this that has been fixed in the latest patch release of universalify.
> ensureFile & ensureFileSync should error when the path is a directory

- package.json
Added '.js' extension to the `main` attribute in package.json, for commpatibility with various loaders or bundlers (webpack, systemjs, browserify,...) or  any other independent lib which may use package.json.
> Added '.js' extension to the <main> attribute in package.json

- docs/copy.md
A found myself struggling because I was using the `copy` function with file source and directory destination (as you can do using `cp`). The error was related to an `unlink` system call not working.
After some digging I landed on #323 but I found that the docs has not been updated.
So here are a few words about this topic.
Thank you :)
> update copy documentation to show differences with cp

- lib/remove/rimraf.js
Backports https://github.com/isaacs/rimraf/commit/38b907fd64656923cc4004ce353e1ad101bd8d1c
Fixes #484
> Use octal notation for chmod values in rimraf.js

- lib/copy-sync/__tests__/copy-sync-preserve-time.test.js
- lib/copy-sync/copy-file-sync.js
- lib/copy/copy.js
- lib/util/utimes.js
Ref: #490.
This is based against the `develop` branch.
Added native `fs.copyFile` and `fs.copyFileSync` to `copy()` and `copySync()`.
> Add native fs.copyFile and fs.copyFileSync to copy() and copySync()

- docs/copy-sync.md
- docs/copy.md
- lib/copy-sync/copy-sync.js
- lib/copy/copy.js
This was deprecated previously, and is now removed.
> BREAKING: Don't allow copy()/copySync()'s filter option to be a Regex

- lib/copy/copy.js
> Fix streams initialization in copyFileFallback

- lib/copy/__tests__/copy-prevent-copying-identical.test.js
- lib/copy/__tests__/copy-prevent-copying-into-itself.test.js
- lib/copy/__tests__/copy.test.js
- lib/copy/copy.js
When applying filter, I think this is a little bit better than before although it still highly depends on the user's filter conditions!
But at least, if users choose their filter conditions intelligently, this way, `copy()` correctly doesn't create dest parent directory since its child path fails on filter.
This is until @RyanZim adds his changes for filter function.
> Create dest parent after applying filter in copy

- lib/fs/index.js
The `lchown` function is [not available on some systems](https://github.com/nodejs/node/blob/master/lib/fs.js#L1150-L1166). Using `fs-extra` there causes a crash:
TypeError: Cannot read property 'name' of undefined
at Object.<anonymous>.exports.fromCallback (../node_modules/universalify/index.js:16:26)
at Object.<anonymous>.api.forEach.method (../node_modules/fs-extra/lib/fs/index.js:50:21)
at Array.forEach (<anonymous>)
This PR makes sure that all commands exist before trying to convert them.
> Fixes fs-extra on linux

- README.md
- docs/copy.md
- docs/emptyDir.md
- docs/ensureDir.md
- docs/ensureFile.md
- docs/ensureLink.md
- docs/ensureSymlink.md
- docs/fs-read-write.md
- docs/move.md
- docs/outputFile.md
- docs/outputJson.md
- docs/pathExists.md
- docs/readJson.md
- docs/remove.md
- docs/writeJson.md
Assuming that [runkit](https://runkit.com/jpeer264/5a532978dcd17c00124b836d) works in all cases.
Should a example be added to every method as well (right under the `Promise usage:`)?
> Add async/await usage example (closes #506)

- docs/copy-sync.md
- docs/copy.md
Could finally made the PR after the Github downtime 👍 
I hope the note for clarifying #537 is understandable. It's also right after the `src`, I took the `dest` note as an example (which I also added in `copy-sync`)
> Docs: add copy note for src

- README.md
`mfs` uses a very outdated version of `fs-extra` that it requires in `dependencies`. I think it should probably be removed.
My package isn't quite as flexible (yet), but it solves my problem for now.
> add fs-extra-debug

- lib/copy-sync/__tests__/copy-sync-prevent-copying-into-itself.test.js
- lib/copy-sync/copy-sync.js
- lib/copy/__tests__/copy-prevent-copying-into-itself.test.js
- lib/copy/copy.js
The problem occurs when:
`src = /tmp/path/src`
`dest = /prefix/tmp/path/src`
> fix function isSrcSubdir in the copy-sync.js and copy.js

- lib/copy-sync/copy-sync.js
- lib/move-sync/index.js
By some reasons on our environment `fs.readSync` from node 8.x throws error when try to read data from position which more than size of file. Here is the test script with logs in comments:
https://gist.github.com/wontem/da867f66324e1cbe712c717b5fefb944
Since we start using node 8.x and fs-extra 5.x - the issue is disappeared (fs-extra uses `copyFileSync` from node) but with node 8.x and fs-extra 3.0.1 the issue is reproducible.
While investigating the problem I've noticed that the method `copySync` from fs-extra 3.0.1 uses extra step in its read loop. To be more safe I want to suggest remove this step from fallback logic for `copySync` and for `moveSync` in fs-extra 5.x
> copySync, moveSync: remove extra step in reading loop

- lib/move/__tests__/move.test.js
- lib/move/index.js
This is with the hope to improve `move()` to handle cross platform compatibility better!
Should resolve #492, #526, #548.
Since OSes are not consistent in error codes (please see my comments in #548), we either have to handle this when errors happen on `fs.rename` based on the OS that current process running, or check dest before the code reaches `fs.rename`. IDK, in my mind, checking dest seemed easier both in terms of implementation and also easier to understand when you read the code.
I like the functional approach for `isSrcSubdir` that @kolgotko introduced in #541. So added here too :grin:
Please feel free to leave any feedback! If we think it looks good, I'll apply the corresponding changes to `moveSync()` as well.
> move: rewrite move to use fs.rename

- lib/copy-sync/copy-sync.js
- lib/copy/copy.js
Overwriting src and dest paths with their resolved ones would result in some side effects like #552. This is a fix to avoid that.
> [BREAKING] copy & copySync: do not overwrite src & dest paths to avoid side effects

- docs/copy-sync.md
- docs/copy.md
- lib/copy-sync/__tests__/copy-sync-preserve-time.test.js
- lib/copy/__tests__/copy-preserve-time.test.js
Update docs and remove tests to reflect this
> copy*() preserveTimestamps: false behavior is OS-dependent

- .travis.yml
- appveyor.yml
- package.json
This is against the `v6-dev` branch.
> BREAKING: Drop builds for Node 4, 5, & 7; add OSX builds & Node 9

- lib/copy-sync/__tests__/copy-sync-case-insensitive-paths.test.js
- lib/copy-sync/__tests__/copy-sync-dir.test.js
- lib/copy-sync/__tests__/copy-sync-file.test.js
- lib/copy-sync/__tests__/copy-sync-prevent-copying-identical.test.js
- lib/copy-sync/__tests__/copy-sync-prevent-copying-into-itself.test.js
- lib/copy-sync/copy-sync.js
- lib/copy/__tests__/copy-case-insensitive-paths.test.js
- lib/copy/__tests__/copy-prevent-copying-identical.test.js
- lib/copy/__tests__/copy-prevent-copying-into-itself.test.js
- lib/copy/__tests__/copy.test.js
- lib/copy/copy.js
fix #565.
`copy` and `copySync`:
Check paths stricter before performing copy and also check case-insensitive paths. Added tests as well. Also, found some `copySync` test file was actually calling `copy` :grin: (I forgot to change it to sync version after copy-paste it!) Fixed that one as well :smile:
> copy*() case-insensitive paths

- lib/copy-sync/copy-sync.js
- lib/copy/copy.js
refactored `copy` and `copySync` so that `startCopy` can have a consistent signature and no need to pass a null param. IDK, I figured that'd be easier to read and understand the code then!
> copy*(): refactor copyDirItems() to avoid passing null param

- lib/__tests__/promise.test.js
- lib/fs/index.js
- lib/index.js
Fixes #577
When fs-extra is loaded on Node.js 10.1.0, an experimental warning is printed:
```
(node:7885) ExperimentalWarning: The fs.promises API is experimental
```
This pull request fixes the problem by defining `fs.promises` as a getter property.
@RyanZim @jprichardson  could you please take a look?
> Fix fs.promises ExperimentalWarning on Node 10.1.0

- package.json
These engines settings should support Node v6 and v8+
(ref: #579)
> Chore: add supported engines

- lib/copy-sync/__tests__/broken-symlink.test.js
- lib/copy-sync/__tests__/copy-sync-dir.test.js
- lib/copy-sync/__tests__/copy-sync-file.test.js
- lib/copy-sync/__tests__/copy-sync-prevent-copying-identical.test.js
- lib/copy-sync/__tests__/copy-sync-prevent-copying-into-itself.test.js
- lib/copy-sync/copy-sync.js
- lib/copy/__tests__/copy-prevent-copying-identical.test.js
- lib/copy/__tests__/copy-prevent-copying-into-itself.test.js
- lib/copy/__tests__/copy.test.js
- lib/copy/__tests__/ncp/broken-symlink.test.js
- lib/copy/copy.js
- lib/json/__tests__/output-json-sync.test.js
- lib/json/__tests__/output-json.test.js
...`copy*()` and long journey of dealing with lots of edge cases and trying to find a proper and yet simple approach to catch as many of those :bug:s as we can!
fix #565. Also possibly fix #546 as we don't use `fs.readlink` anymore to check the paths.
I guess it's breaking as for the case of symlinks, we throw error with descriptive message instead of silently return.
- use `ino` to check if src and dest are the same (Thanks to @TanninOne for bringing that idea). This is beyond checking just paths. Since `fs.lstat` stats the link itself not the actual file that it points to, we have to do an extra `fs.stat` to get the actual `ino` of both src and dest. This essentially relies on node's internal api to give us correct `ino`s! This also catches the cases like when dest parent is a symlink …
> [BREAKING] copy*(): use ino to check identical paths

- lib/copy-sync/__tests__/copy-sync-readonly-dir.test.js
- lib/copy-sync/copy-sync.js
- lib/copy/__tests__/copy-readonly-dir.test.js
- lib/copy/copy.js
Fix for https://github.com/jprichardson/node-fs-extra/issues/599
There are two distinct changes needed to fix this:
- When creating a new directory, don't specify the file mode
- Switch chmod and recursive copy so chmod happens after
I ran the tests locally on my MacBook. 3 tests (related to `preserveTimestamps` and `hasMillisResSync`) failed both before and after the change. I included a new test (hopefully close enough to the style already in use) that fails without my fix, and succeeds with it.
> Set new directory mode after copying files (MacOS fix)

- docs/copy-sync.md
- docs/copy.md
- docs/emptyDir.md
- docs/ensureDir.md
- docs/ensureFile.md
- docs/ensureLink.md
- docs/ensureSymlink-sync.md
- docs/ensureSymlink.md
- docs/move-sync.md
- docs/move.md
- docs/outputFile-sync.md
- docs/outputFile.md
- docs/outputJson-sync.md
- docs/outputJson.md
- docs/readJson-sync.md
- docs/readJson.md
- docs/remove.md
- docs/writeJson-sync.md
- docs/writeJson.md
Node's docs uses the pattern of `,` after `[` for optional parameters. For instance, please take a look at [this one](https://nodejs.org/api/fs.html#fs_fs_appendfilesync_path_data_options). So, figured why not following the same pattern!
> fix docs to be consistent with node docs

- docs/ensureDir-sync.md
- docs/ensureDir.md
Node fs's `mkdir` (https://nodejs.org/api/fs.html#fs_fs_mkdir_path_mode_callback) supports mode specification. After reviewing the source
`fs-extra` does as well, but is not documented. Update the documentation
to include the `options` parameter and provide a few examples of using
`mode`.
> Show support for mode

- lib/move-sync/__tests__/move-sync-prevent-moving-into-itself.test.js
- lib/move-sync/__tests__/move-sync.test.js
- lib/move-sync/index.js
- package.json
fix #608.
Refactored `moveSync` to be consistent with `move`. Also removed unnecessary `rimraf` package from dev-deps.
> [BREAKING] moveSync: refactor to use renameSync

- lib/copy-sync/__tests__/broken-symlink.test.js
- lib/copy-sync/__tests__/copy-sync-case-insensitive-paths.test.js
- lib/copy-sync/__tests__/copy-sync-dir.test.js
- lib/copy-sync/__tests__/copy-sync-file.test.js
- lib/copy-sync/__tests__/copy-sync-preserve-time.test.js
- lib/copy-sync/__tests__/copy-sync-prevent-copying-identical.test.js
- lib/copy-sync/__tests__/copy-sync-prevent-copying-into-itself.test.js
- lib/copy-sync/__tests__/copy-sync-readonly-dir.test.js
- lib/copy-sync/__tests__/symlink.test.js
- lib/copy-sync/copy-sync.js
- lib/copy/__tests__/copy-case-insensitive-paths.test.js
- lib/copy/__tests__/copy-gh-89.test.js
- lib/copy/__tests__/copy-preserve-time.test.js
- lib/copy/__tests__/copy-prevent-copying-identical.test.js
- lib/copy/__tests__/copy-prevent-copying-into-itself.test.js
- lib/copy/__tests__/copy-readonly-dir.test.js
- lib/copy/__tests__/copy.test.js
- lib/copy/copy.js
fix #613.
Fixed the issue of infinite loop that would used to happen for cases like bind-mounted directories with subdirectory that would end up creating a lot of recursive same subdirectories and finally failing with `ENAMETOOLONG` error.
With this fix, we catch these weird cases and throw error with descriptive message.
Also, cleaned up some tests.
> copy*(): fix copying bind-mounted directories

- lib/copy-sync/copy-sync.js
- lib/copy/copy.js
- lib/move-sync/__tests__/move-sync-case-insensitive-paths.test.js
- lib/move-sync/__tests__/move-sync-prevent-moving-into-itself.test.js
- lib/move-sync/__tests__/move-sync.test.js
- lib/move-sync/index.js
- lib/move/__tests__/move-case-insensitive-paths.test.js
- lib/move/__tests__/move-prevent-moving-into-itself.test.js
- lib/move/__tests__/move.test.js
- lib/move/index.js
fix #614 and #608.
Added the same _paths checking_ that we use in `copy*()` to `move*()`. This will avoid unexpected behavior and improve reliability of the function!
> [BREAKING] move*(): check paths before moving

- lib/remove/rimraf.js
Lately I've been seeing a lot of errors like this on Windows:
> `ERROR: ENOTEMPTY: directory not empty, rmdir 'C:\some\folder'`
The Windows OS prevents a folder from being removed while file handles are still open.  Certain processes such as virus scanners and compiler environments watch folders for changes.  After a folder is removed, they take a little while to realize this and unregister their handlers.  In my empirical tests, it can occasionally take around 100ms - 200ms.
**fs-extra** already provides some protection against this:
[rimraf.js](https://github.com/jprichardson/node-fs-extra/blob/ab254b1efdefe0b05f73e96fb3f1d17902e03942/lib/remove/rimraf.js#L288)
```js
// We only end up here once we got ENOTEMPTY at least once, and
// at this point, we are guaranteed to have removed all …
```
> Fix removeSync() to eliminate spurious ENOTEMPTY errors on Windows

- lib/util/__tests__/stat.test.js
- lib/util/stat.js
fixes #678.
- resolve paths before parsing in `util/stat.js`
- add `util/stat` tests
> util/stat: fix max call stack size exceeded

- lib/fs/__tests__/realpath.test.js
- lib/fs/index.js
Closes https://github.com/jprichardson/node-fs-extra/pull/650
> Add support for fs.realpath.native in envs that support it

- lib/__tests__/promise.test.js
- lib/copy-sync/__tests__/broken-symlink.test.js
- lib/copy-sync/__tests__/copy-sync-file.test.js
- lib/copy-sync/__tests__/copy-sync-preserve-timestamp.test.js
- lib/copy-sync/__tests__/symlink.test.js
- lib/copy-sync/copy-sync.js
- lib/copy/__tests__/copy-preserve-timestamp.test.js
- lib/copy/__tests__/copy.test.js
- lib/copy/__tests__/ncp/broken-symlink.test.js
- lib/copy/__tests__/ncp/ncp.test.js
- lib/copy/__tests__/ncp/symlink.test.js
- lib/copy/copy.js
- lib/ensure/__tests__/symlink-paths.test.js
- lib/json/__tests__/output-json-sync.test.js
- lib/json/__tests__/output-json.test.js
- lib/move-sync/__tests__/move-sync.test.js
- lib/move/__tests__/move.test.js
- lib/util/__tests__/utimes.test.js
- package.json
> Upgrade to standard v12

- lib/ensure/symlink-paths.js
- lib/mkdirs/__tests__/clobber.test.js
- lib/mkdirs/__tests__/race.test.js
- package.json
I have fixed the following error.
```
node-fs-extra/lib/ensure/symlink-paths.js:37:9: Unnecessarily quoted property 'toCwd' found.
node-fs-extra/lib/ensure/symlink-paths.js:38:9: Unnecessarily quoted property 'toDst' found.
node-fs-extra/lib/ensure/symlink-paths.js:48:11: Unnecessarily quoted property 'toCwd' found.
node-fs-extra/lib/ensure/symlink-paths.js:49:11: Unnecessarily quoted property 'toDst' found.
node-fs-extra/lib/ensure/symlink-paths.js:58:13: Unnecessarily quoted property 'toCwd' found.
node-fs-extra/lib/ensure/symlink-paths.js:59:13: Unnecessarily quoted property 'toDst' found.
node-fs-extra/lib/ensure/symlink-paths.js:73:7: Unnecessarily quoted property 'toCwd' found.
node-fs-extra/lib/ensure/symlink-paths.js:74:7: Unnecessarily quoted property 'toDst' found. …
```
> Upgrade 'standard'

- lib/util/stat.js
The resolution of https://github.com/jprichardson/node-fs-extra/issues/657 relies on Node >= 10.5, but actually leaves the issue not fixed on previous versions of Node (in particular, for the OP, who reported the issue on Node 8.11.3). The issue particularly problematic and frequent in automated setups, such as running tests that create files in sequence, where it is likely to happen.
This PR minimizes the frequency of this issue by comparing additional `fs.Stats` values when `Bigint` support is not available. Note that the check is still heuristic: different stats prove they are different files*, but while same stats do not prove they are the same, we must err on the side of caution and still treat them as the same file.
(*) **Race condition**: comparing file stats before performing a …
> Add heuristics to stats.ino comparison when bigint is not available

- package.json
fs-extra is probably the most popular promise-supporting fs library on npm, but if you [search npmjs.com for "fs promise"](https://www.npmjs.com/search?q=fs+promise), it doesn’t even show up. This change should hopefully fix that :-).
> Add "promise" to keywords on npm

- lib/remove/__tests__/remove.test.js
Hi,
The async operations of fse.remove, fse.pathExists, and setInterval may interleave (race) causing the callback of fse.pathExists be called twice with variable itDoes=false. In this case, error `Error: done() called multiple times` is thrown, making the test flaky.
> fix flaky test in remove.test.js

- lib/copy/__tests__/ncp/ncp.test.js
Hi, 
Function `readDirFiles` may due to some race return object `srcFiles` with different structures. In particular, if property `sub` (an object) comes before `a` (string), function `filter` fails to remove `a` as it returns after the recursive call. This case makes the test flaky. 
Error:
```
Uncaught AssertionError [ERR_ASSERTION]: Input A expected to strictly deep-equal input B:
+ expected - actual ... Lines skipped
{
-   a: 'Hello world\n',
b: 'Hello ncp\n',
...
}
}
+ expected - actual
{
-  "a": "Hello world\n"
"b": "Hello ncp\n"
"c": ""
"d": ""
"e": ""
at readDirFiles (lib/copy/__tests__/ncp/ncp.test.js:58:20)
```
> fix a flaky test in ncp.test.js

- lib/ensure/__tests__/create.test.js
- lib/ensure/file.js
Closes #698; includes all changes from there, plus my changes. CC @lukechilds
> Improve ensurefile error

- package.json
istanbul is deprecated, nyc is the successor.
> Switch from istanbul to nyc

- README.md
- docs/fs-read-write-writev.md
- lib/fs/__tests__/multi-param.test.js
- lib/fs/index.js
Added:
- `fs.writev`
- `fs.opendir`
> Update fs promise shims to support latest Node functions

- lib/copy-sync/__tests__/copy-sync-preserve-timestamp.test.js
- lib/copy-sync/copy-sync.js
- lib/copy/__tests__/copy-preserve-timestamp.test.js
- lib/copy/copy.js
This PR provides a fix for the recently failing "copy-preserve-timestamps" (sync & async) tests on MacOS (partial fix for #571). (I believe they have been incorrect for a while but passed by chance due to timing and the coarse 1-s resolution time of HFS+.)
The main observation is that after copying a source file, the `atime` of that file may be modified (probably always will, due to the copy operation implicitly updating the `atime` when it `read`s from the file according to https://nodejs.org/docs/latest-v8.x/api/fs.html#fs_stat_time_values), so if we want to provide a true `preserveTimestamps` option, we need to re-read the source `atime` and use that value when updating the destination timestamps.
> Update dest atime after copy/copy-sync

- lib/copy-sync/__tests__/copy-sync-preserve-timestamp.test.js
- lib/copy-sync/copy-sync.js
- lib/copy/__tests__/copy-preserve-timestamp.test.js
- lib/copy/copy.js
Resolves #754.
- Removed `copyFileFallback` from `copy` and `copySync` since there was no need for it.
> copy*(): remove copyFileFallback

- lib/fs/__tests__/multi-param.test.js
- lib/util/__tests__/stat.test.js
- lib/util/stat.js
- package.json
https://github.com/RyanZim/at-least-node
Refs https://github.com/jprichardson/node-fs-extra/pull/756#discussion_r376420498
> Use at-least-node instead of homespun version sniffing

- .gitignore
- .npmrc
Lockfiles are an anti-pattern for libraries; we don't check ours into git, but it's preferable not to even use one.
> Don't generate package-lock.json; instead of just ignoring it

- lib/__tests__/promise.test.js
- lib/copy/__tests__/copy.test.js
- lib/util/stat.js
Fixes #762
Review commit-by-commit for your sanity.
> Refactor internal stat utils

- lib/json/__tests__/output-json-sync.test.js
- lib/json/__tests__/output-json.test.js
- lib/json/index.js
- lib/json/jsonfile.js
- lib/json/output-json-sync.js
- lib/json/output-json.js
- package.json
- Upgrade jsonfile (Fixes #745)
- Make outputJson() mutation-proof (Fixes #702)
- I have added a test case for this, and verified that it fails without my fix
---
Review commit-by-commit for clarity.
> JSON updates

- .github/issue_template.md
As a lot of bugs just came in with the wrong Node version I added a small hint
> Docs: add hint for supported Node.js version

- docs/copy-sync.md
- docs/copy.md
- docs/emptyDir.md
- docs/ensureDir-sync.md
- docs/ensureDir.md
- docs/ensureFile.md
- docs/ensureLink-sync.md
- docs/ensureLink.md
- docs/ensureSymlink-sync.md
- docs/ensureSymlink.md
- docs/move-sync.md
- docs/move.md
- docs/outputFile-sync.md
- docs/outputFile.md
- docs/outputJson-sync.md
- docs/outputJson.md
- docs/pathExists.md
- docs/readJson-sync.md
- docs/readJson.md
- docs/remove-sync.md
- docs/remove.md
- docs/writeJson-sync.md
- docs/writeJson.md
- package.json
Just a little improvement in docs! Resolves #753.
> Improve docs

- docs/ensureDir-sync.md
- docs/ensureDir.md
- docs/outputJson-sync.md
- docs/outputJson.md
- docs/writeJson-sync.md
- docs/writeJson.md
Small things but I believe still important as IMO inconsistency kills the heart of a good project :grin:!
> Consistentify types in docs

- .travis.yml
- appveyor.yml
- lib/ensure/__tests__/create.test.js
- lib/remove/__tests__/remove.test.js
Fixes #798
`writeFileSync` requires a data parameter
Also add Node 14 to CI
> Fix tests on Node 14

- lib/remove/rimraf.js
This fixes cross-VM type issues in Jest #804 .
See https://github.com/isaacs/rimraf/commit/aa50e0298f66b3375045e8d9d86992d696a56b09
> fix: do not check errors with `instanceof`.

- README.md
Add a link to npm package [fse-cli](https://www.npmjs.com/package/@atao60/fse-cli), a CLI for fs-extra. Not all fs-extra functions are embedded yet, but those available are fully functional and tested.
> Docs: add fse-cli to the README

- lib/fs/__tests__/rm.test.js
- lib/fs/index.js
> Add promise support for fs.rm()

- lib/copy-sync/__tests__/copy-sync-dir.test.js
- lib/copy/__tests__/copy.test.js
Fixes tests being broken locally, mentioned in https://github.com/jprichardson/node-fs-extra/pull/860#pullrequestreview-571128655.
Birth time is unavailable on tmpfs:
```console
$ LANG=C stat /tmp/fs-extra/
File: /tmp/fs-extra/
Size: 60              Blocks: 0          IO Block: 4096   directory
Device: 31h/49d Inode: 32254       Links: 3
Access: (0755/drwxr-xr-x)  Uid: ( 1000/ chalker)   Gid: ( 1000/ chalker)
Access: 2021-01-19 16:38:51.439969625 +0300
Modify: 2021-01-19 16:38:55.031733100 +0300
Change: 2021-01-19 16:38:55.031733100 +0300
Birth: -
```
> test: fix birthtime not available on tmpfs on Linux

- lib/copy-sync/copy-sync.js
- lib/copy/copy.js
Hi :)
This is a minor update to code quality. The expression `destStat` on line `102` and `146` will always return `true`. This is bad code practice and is described in [CWE 571](https://cwe.mitre.org/data/definitions/571.html).
I found this issue while doing a security audit of our dependencies. It's not a big deal but might as well be fixed. I have tried to mimic your existing code style in my rewrite, but feel free to rewrite it in another way.
Let me know if you want me to explain in more detail why this is bad practice.
> Minor improvement to code quality

- lib/ensure/__tests__/link.test.js
- lib/ensure/__tests__/symlink.test.js
- lib/ensure/link.js
- lib/ensure/symlink.js
- lib/util/stat.js
Fixes #786 
Fixes #870
CC @cxres
> BREAKING: Ensure existing dest correct type/target in ensureLink/Symlink

- lib/copy-sync/copy-sync.js
- lib/copy/copy.js
Replaces & closes #812
Implements suggestions in https://github.com/jprichardson/node-fs-extra/pull/812#pullrequestreview-432759032; since that PR was abandoned without updates.
> copy*(): Error when unknown file type is encountered

- lib/empty/index.js
This theoretically should be faster, since we're launching all the remove operations at once, instead of one-by-one.
> Convert emptyDir() to async function; remove items in parallel

- docs/copy-sync.md
- docs/copy.md
> Clarify docs for copy*() filter

- lib/remove/index.js
Fixes #806
Technically a breaking change since this removes the undocumented ability to pass options to remove*()
> BREAKING: Use fs.rm/rmSync where supported

- lib/copy-sync/__tests__/copy-sync-file.test.js
- lib/copy-sync/copy-sync.js
- lib/copy/__tests__/copy.test.js
- lib/copy/copy.js
Fixes #809
We need to check filter before creating a parent directory for `dest`, in case the filter cancels the entire operation. After creating the parent (if needed), we were calling a function that rechecked the filter, which wasn't needed, and resulted in the filter fn being called twice at the root level.
With these changes, we should possibly consider renaming some functions, as it doesn't seem to make much sense anymore.
> Ensure copy filter fn is not called more than needed

- docs/move-sync.md
- docs/move.md
> Clarify move*() docs

- .travis.yml
- appveyor.yml
- package.json
~Not needed if we merge https://github.com/jprichardson/node-fs-extra/pull/881 and kill the old CI providers.~ Will need edits; still need `engines` bump.
> BREAKING: Drop Node 10 support

- lib/__tests__/promise.test.js
- lib/fs/index.js
- lib/index.js
Refs #886
Only for merge after Node v10 is dropped.
> BREAKING: Remove special handling of fs.promises

- lib/util/__tests__/stat.test.js
- lib/util/stat.js
Refs #886
After https://github.com/jprichardson/node-fs-extra/pull/893
> BREAKING: Use bigint everywhere

- lib/move-sync/__tests__/move-sync.test.js
- lib/move-sync/move-sync.js
- lib/move/__tests__/move.test.js
- lib/move/move.js
Fixes #819.
Do not create parent directory if it is root. We run tests for this only on windows, moving to root on unix-like systems requires sudo privileges.
> move: do not create parent directory if it is root

- lib/copy/__tests__/ncp/ncp-error-perm.test.js
This test tries to create a directory where the current user does not have the
permissions to do so and expects a failure. However, the root user is by design
always allowed to do that (ignoring file permissions). So we must skip the test
in these cases then.
This fixes https://github.com/jprichardson/node-fs-extra/issues/898
> Skip the ncp / error / dest-permission test if running as root

- package.json
Add `"sideEffects": false` to package.json to allow frameworks that mix client and server code in the same files to tree-shake out fs-extra from client bundles.
> chore: "sideEffects": false

- lib/copy/__tests__/ncp/ncp.test.js
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> refactor: replace deprecated String.prototype.substr()

- lib/fs/__tests__/realpath.test.js
- lib/fs/index.js
#887 causes a few regressions, not because of `fs-extra`, but due to other dependencies who are using `fs-extra`.
**The general gist is that others' improper monkey-patches of `fs` should not impact the import and initialisation of `fs-extra`.**
---
When `fs.realpath.native` is `undefined` caused by the improper handling by other packages, it inevitably affected the import and initialisation of `fs-extra` as the `universalify` would not be able to parse this line properly.
https://github.com/jprichardson/node-fs-extra/blob/7edcb16a06e041826af3303f961866bf3b243dae/lib/fs/index.js#L57
**It results in `fs-extra` throwing errors on import, even if the `fs-extra.realpath.native` API is not being used during runtime.**
And the stacktrace shows:
```
TypeError: Cannot read property 'name' of …
```
> Revert check for fs.realpath.native (#887)

- lib/__tests__/promise.test.js
- lib/move/__tests__/move.test.js
- lib/move/move.js
Fixes #947
Closes #948
Will merge in a few days if no objections.
> Allow passing undefined opts to move()

- lib/copy/copy-sync.js
- lib/copy/copy.js
To have consistent warnings from https://github.com/jprichardson/node-fs-extra/pull/953#issuecomment-1092663914 by @JPeer264 
> Yes `process.emitWarning` sounds also like a great option to add (just my opinion on it). However, a separate PR would be nice if you want to go the extra mile as we squash our PRs. @manidlou @RyanZim @jprichardson any objections?
Prints out via `process.emitWarning` in the following format:
> refactor: replace console.warn with process.emitWarning

- lib/fs/__tests__/multi-param.test.js
- lib/fs/index.js
Depends on https://github.com/jprichardson/node-fs-extra/pull/969
Somehow we missed adding support for this; better late than never!
> Add promise support for fs.readv

- package.json
Shut up `npm audit` and use latest `standard`. Will merge in a few days if no objection.
> Upgrade devDeps

- lib/copy/copy-sync.js
- lib/copy/copy.js
Fixes #965 cc @c-vetter
Exact approach in https://github.com/nodejs/node/pull/44922 didn't seem appropriate.
> Run copy*() filter before running fs.stat() on items

- lib/copy/copy-sync.js
- lib/copy/copy.js
As per https://github.com/nodejs/node/pull/39372#discussion_r1001179295; haven't gotten a response from @bcoe there yet
Resolves https://github.com/jprichardson/node-fs-extra/issues/918
Hope this logic is right.
> Remove unneeded and buggy stats check

- package.json
> fix: add package main field for TypeScript support

- lib/move/__tests__/move-preserve-timestamp.test.js
- lib/move/__tests__/move-sync-preserve-timestamp.test.js
- lib/move/move-sync.js
- lib/move/move.js
This PR resolves issue: #992.
These test files are pretty similar, I just took the `copy` method test files as a blueprint, and it seems we can make some refactoring here and there. I'm open to any suggestions!
> Fix preserving timestamp when the move command is executing

- README.md
- lib/move/__tests__/cross-device-utils.js
- lib/move/__tests__/move-preserve-timestamp.test.js
- lib/move/__tests__/move-sync-preserve-timestamp.test.js
- lib/move/__tests__/move-sync.test.js
- lib/move/__tests__/move.test.js
Especially since https://github.com/jprichardson/node-fs-extra/pull/994, functionally equivalent code was being needlessly duplicated. This centralizes into one place the configuration for locally testing cross-device moves; and unifies test code considerably.
> Unify cross-device move test configuration/logic

- lib/util/stat.js
In this case, `reduce` can be simplified via `every'.
> Simplify reduce for checking match

- lib/output-file/index.js
The PR is a part of the proposal https://github.com/jprichardson/node-fs-extra/issues/1020.
All test cases pass: https://github.com/SukkaW/node-fs-extra/actions/runs/6599334843.
> Refactor `outputFile` APi in async/await

- lib/ensure/file.js
- lib/ensure/link.js
- lib/ensure/symlink-paths.js
- lib/ensure/symlink-type.js
- lib/ensure/symlink.js
The PR is a part of the proposal https://github.com/jprichardson/node-fs-extra/issues/1020.
All test cases pass: https://github.com/SukkaW/node-fs-extra/actions/runs/6599300023.
> Refactor `create*`/`ensure*` API in async/await

- lib/copy/__tests__/copy-broken-symlink.test.js
- lib/copy/__tests__/copy-preserve-timestamp.test.js
- lib/copy/__tests__/ncp/broken-symlink.test.js
- lib/copy/__tests__/ncp/ncp-error-perm.test.js
- lib/copy/__tests__/ncp/ncp.test.js
- lib/copy/__tests__/ncp/symlink.test.js
- lib/copy/copy.js
- lib/copy/index.js
- lib/util/__tests__/utimes.test.js
- lib/util/stat.js
- lib/util/utimes.js
The PR is the first part of proposal #1020:
- The PR only migrates the `copy` API. Other APIs will be migrated in the following PRs
- The PR adds Promise-based implementations for some utility functions. The callback-based implementations are retained, but they will be removed once the rest of the library has migrated to Promise-based implementations.
> Refactor `copy` API in async/await

- lib/move/__tests__/move.test.js
- lib/move/index.js
- lib/move/move.js
The PR is the final part of #1020.
> Refactor `move` API to async/await

- lib/copy/copy.js
The PR uses a technique similar to #885 to speed up the recursive copy operation.
As `fs-extra` is built on top of `graceful-fs`, this change won't cause `EMFILE: too many open files` as `graceful-fs` will exponentially backoff and retry.
> Perf: copying dir contents in parallel

- lib/copy/copy-sync.js
- lib/copy/copy.js
The PR closes #972.
The `readdir` returns the contents of a directory all at once, which can be slow (and blocking) when a directory contains many items. The `opendir` returns the contents of a directory one at a time.
Unlike the original Node.js changes (which copy items one by one), this PR retains copy in parallel (as introduced in #1026).
> Refactor `copy` to use `opendir`

- .github/workflows/ci.yml
- lib/fs/index.js
Fixes #1044
Somehow, I added a comment about `fs.cp` but never added it to the list :man_shrugging:
> Add promise support for missing fs methods
